apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_USER: dXNlcg==       # Base64 de 'user'
  MYSQL_PASSWORD: cGFzc3dvcmQ= # Base64 de 'password'
  MYSQL_DATABASE: ZGF0YWJhc2U= # Base64 de 'database'
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3M=  # Base64 de 'rootpass'
